services:
  app:
    build: .
    container_name: anime-vtuber
    ports:
      - "5173:5173"   # Vite frontend
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - BACKEND_PORT=8000
      - FRONTEND_PROXY=1
      # Allow backend in container to reach host Ollama
      - LLM_HOST=http://host.docker.internal:11434
    # Ensure Vite uses correct host inside container
    working_dir: /app
    command: sh -c "node frontend/scripts/sync-assets.mjs && (python3 backend/server.py &) && npm --prefix frontend run dev"


